(297) Add support for stub nameservers and fix docs
voxpupuli/puppet-unbound pull request #298
Opened 2022-06-03 15:34 UTC by b4ldr

and a new parameter to unbound::stub to support `stub-host`

fixes #297

2022-06-08 21:13 UTC, ekohl requested changes
Overall :+1: but there are a few typos in docs

2022-06-08 21:13 UTC, ekohl commented on README.md
> +  namservers => [ 'ns1.example.com', 'ns2.example.com' ],
```suggestion
  nameservers => [ 'ns1.example.com', 'ns2.example.com' ],
```

2022-06-08 21:13 UTC, ekohl commented on README.md
> +  address => [ 10.0.0.53', '10.0.0.10@10053'],
Would be nice to keep this aligned

2022-06-08 21:13 UTC, ekohl commented on README.md
> +    nameserveres:
```suggestion
    nameservers:
```

2022-06-08 21:13 UTC, ekohl commented on manifests/stub.pp
> +  Array[Stdlib::Host]                                 $nameservers = [],
```suggestion
  Array[Stdlib::Host]                                $nameservers = [],
```

2022-06-16 18:45 UTC, b4ldr commented on README.md
> +  address => [ 10.0.0.53', '10.0.0.10@10053'],
done sorry it took a while to come back

2022-06-17 07:52 UTC, bastelfreak approved these changes

2022-06-17 07:52 UTC, merged